# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko_pacjenta', models.CharField(max_length=32)),
                ('imie_pacjenta', models.CharField(max_length=32)),
                ('pesel', models.IntegerField(max_length=11)),
                ('data_rejestracji', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_wizyty', models.DateTimeField(blank=True, null=True)),
                ('uwagi', models.CharField(max_length=200)),
                ('RECEPCJONISTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
