# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcja', '0002_auto_20170610_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejestracja',
            name='pesel',
        ),
    ]
